### ISSUE TITLE
Loading a track can **SOMETIMES** cause note placements to be offset

### ISSUE THREAD

**Issue by OrangeW2** [megalon/BeatSaber-UnofficialTrackEditor#9]
Can't reproduce, however sometimes upon loading a track, placing new notes is placed below your actual cursor, whilst the seek bar is accurate

**Comment by megalon** [comment]
Marking this as fixed because I believe that this was due to the "_time" value getting clamped to the size of the grid. 
Time is now stored separately from the pixel position on the grid, so it should not happen anymore.

This does seem like the kind of issue that will keep cropping up, so will reopen if it does.
Thanks!
